name: Haskell CI
# Adopted from https://kodimensional.dev/github-actions

# Trigger the workflow on push or pull request, but only for the master branch
on:
  pull_request:
  push:
  
jobs:

  hlint:
    name: HLint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: 'Set up HLint'
      uses: rwe/actions-hlint-setup@v1
      with:
        version: '3.3.6'

    - name: 'Run HLint'
      uses: rwe/actions-hlint-run@v1
      with:
        path: src/
        fail-on: warning

  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  stack:
    name: stack / ghc ${{ matrix.ghc }}
    runs-on: ubuntu-latest            #${{ matrix.os }}
    strategy:
      matrix:
        stack: ["2.7.5"]
        ghc: ["8.8.4", "8.10.2", "9.0.2"]

    steps:
      - uses: actions/checkout@v2
        if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/master'

      - uses: actions/setup-haskell@v1.1.4
        name: Setup Haskell Stack
        with:
          ghc-version: ${{ matrix.ghc }}
          stack-version: ${{ matrix.stack }}

      - uses: actions/cache@v2
        name: Cache ~/.stack
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{ matrix.ghc }}-stack

      - name: Build
        run: |
          stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks

      - name: Test
        run: |
          stack test --system-ghc
